// Theme colors and constants matching the React project EXACTLY
export const theme = {
  colors: {
    background: '#ffffff',
    foreground: '#263D42',
    card: '#ffffff',
    cardForeground: '#263D42',
    primary: '#4FB286',
    primaryForeground: '#ffffff',
    secondary: '#CEB5A7',
    secondaryForeground: '#263D42',
    muted: '#f5f4f3',
    mutedForeground: '#6b7280',
    accent: '#f0ede9',
    accentForeground: '#263D42',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: 'rgba(38, 61, 66, 0.15)',
    input: 'transparent',
    inputBackground: '#f9f8f6',
    switchBackground: '#d1cfc8',
    ring: '#4FB286',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    '2xl': 24,
    '3xl': 32,
    '4xl': 40,
    '5xl': 48,
    '6xl': 64,
  },
  borderRadius: {
    sm: 4,
    md: 6,
    lg: 10,
    xl: 12,
    '2xl': 16,
    full: 9999,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    base: 16,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    '2xl': 24,
    xxxl: 32,
  },
  fontWeight: {
    normal: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
    },
  },
};
