name: Update Main Repo from Front

on:
  push:
    branches:
      - main

jobs:
  update-main-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone main repo
        run: |
          git clone https://x-access-token:${{ secrets.MAIN_REPO_TOKEN }}@github.com/${{ secrets.MAIN_REPO_OWNER }}/IWAProject.git
          cd IWAProject
          git checkout main

          # Inject token into submodule URLs
          git config -f .gitmodules submodule.front.url https://x-access-token:${{ secrets.MAIN_REPO_TOKEN }}@github.com/${{ github.repository }}.git
          git config -f .gitmodules submodule.back.url https://x-access-token:${{ secrets.MAIN_REPO_TOKEN }}@github.com/${{ secrets.MAIN_REPO_OWNER }}/IWAProject-Back.git

          git submodule sync
          git submodule update --init --recursive

          # Update front submodule to latest main
          cd front
          git fetch origin main
          git checkout origin/main
          cd ..

          git add front
          git commit -m "chore: update front submodule to latest main" || echo "No changes to commit"
          git push origin main

      - name: Notify Update Success
        if: success()
        run: echo "🚀 Successfully updated main repo with front changes!"
